/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.FormController;
import Model.DatabaseInserter;
import Model.DatabaseRetriever;
import Model.Permintaan;
import Model.Pertemuan;
import Model.Waktu;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class FormPengaju extends javax.swing.JPanel {
    private Permintaan permintaan;
    /**
     * Creates new form FormPengaju
     */
    public FormPengaju() {
        initComponents();
        tanggalSpinner.setModel(new javax.swing.SpinnerDateModel());
        tanggalSpinner.setEditor(new javax.swing.JSpinner.DateEditor(tanggalSpinner, "dd/MM/yyyy"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sesiSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ajukanButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tanggalSpinner = new javax.swing.JSpinner();
        jamSpinner = new javax.swing.JSpinner();
        menitSpinner = new javax.swing.JSpinner();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("FORM PENGAJUAN PERGANTIAN RUANGAN");

        jLabel6.setText("Sesi Pergantian:");

        sesiSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jLabel4.setText("Waktu Sesi Pergantian Dimulai: ");

        jLabel7.setText("ID:");

        ajukanButton.setText("Ajukan");
        ajukanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajukanButtonActionPerformed(evt);
            }
        });

        jLabel8.setText(":");

        jLabel10.setText("Hari/Tanggal Sesi Pergantian Dimulai:");

        tanggalSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        jamSpinner.setModel(new javax.swing.SpinnerNumberModel(7, 7, 18, 1));

        menitSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ajukanButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tanggalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jamSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sesiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tanggalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sesiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(menitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ajukanButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ajukanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajukanButtonActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(idTextField.getText());
        DatabaseRetriever databaseRetriever = new DatabaseRetriever();
        boolean existingPertemuan = databaseRetriever.checkPertemuanExist(id);
        if (existingPertemuan == false) {
            JOptionPane.showMessageDialog(this, "Pertemuan dengan ID tersebut tidak ditemukan.");
            return;
        }
        Pertemuan pertemuan = databaseRetriever.retrieveDataPertemuan(id);
        boolean existingPermintaan = databaseRetriever.checkPermintaanExist(id);
        if (existingPermintaan == true) {
            JOptionPane.showMessageDialog(this, "Permintaan dengan ID tersebut sudah ada dalam database.");
            return;
        }
        permintaan = new Permintaan();
        permintaan.setId(id);
        permintaan.setTanggalSebelum(pertemuan.getTanggal());
        Date date = (Date) tanggalSpinner.getValue();
        LocalDate tanggal = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        permintaan.setTanggalSesudah(tanggal);
        permintaan.setSesiSebelum(pertemuan.getSesi());
        permintaan.setSesiSesudah((int) sesiSpinner.getValue());
        Waktu waktuMulai = new Waktu();
        waktuMulai.setJam((int) jamSpinner.getValue());
        waktuMulai.setMenit((int) menitSpinner.getValue());
        permintaan.setWaktuMulai(waktuMulai);
        
        FormController form = new FormController(permintaan);
        
        if(!form.validatePermintaan()){
            List<String> errorMessages = form.getErrorMessages();
            String message = "Data Tidak Valid. Perbaiki error berikut:\n";
            for (String errorMessage : errorMessages) {
                message += (errorMessage + "\n");
            }
            JOptionPane.showMessageDialog(this, message);
        }else{
            // Memasukkan data ke dalam database permintaan
            DatabaseInserter databaseInserter = new DatabaseInserter();
            databaseInserter.insertPermintaan(permintaan);
            this.setVisible(false);
            JOptionPane.showMessageDialog(this, "Permintaan berhasil diajukan");
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_ajukanButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajukanButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jamSpinner;
    private javax.swing.JSpinner menitSpinner;
    private javax.swing.JSpinner sesiSpinner;
    private javax.swing.JSpinner tanggalSpinner;
    // End of variables declaration//GEN-END:variables
}
